# This is a basic workflow to help you get started with Actions

name: Creating Database backup 

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Executing Azure cli installation script
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      
      - name: Authenticating to Azure Platform | az login
        run: az login --service-principal --username ${{ secrets.SERVICE_PRINCIPAL_CLIENT_ID }} --password ${{ secrets.SERVICE_PRINCIPAL_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # PIP install
      # - name: Install Dependencies
      #  run: pip install -r requirements.txt

      # Sync
      - name: Making backup
        run: python mysql_backup_db.py
        env:
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      
      - name: Getting path
        run: pwd && ls -all
      
      - name: Uploading blob container
        run: az storage blob upload --account-name mysqlbackups007 --container-name database-backups --name edc-demo_backup.sql --file edc-demo_backup.sql